### ISSUE TITLE
tests fail with error ' bad syntax in: (for/fold/derived (for/fold ((res '

### ISSUE THREAD

**Issue by spdegabrielle** [videolang/idmt#2]
Apologies - this was poorly logged originally

I get this error when I attempt to run any of the tests, starting with tests/example.rkt

Kind regards, 

Stephen

---
The '#:result' doesn't look right? I can't find it in the reference for for/fold 

editor/stdlib.rkt:346:4

http://docs.racket-lang.org/reference/for.html?q=for%2Ffold#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._for%2Ffold%29%29

(for/fold ([accum-id init-expr] ...) (for-clause ...) body-or-break ... body)

---
Welcome to DrRacket, version 6.11 [3m].

Language: racket/base, with debugging; memory limit: 128 MB.
. ../editor/stdlib.rkt:346:4: for/fold/derived: bad syntax in: (for/fold/derived (for/fold ((res (quote ())) (w 0) (h 0) (x (+ l sx)) (y (+ t sy)) #:result (values (reverse res) (max sw (+ w l r)) (max sh (+ h t b)) l t r b)) ((i (in-list editor-list))) (cond ((and stretchable? (is-a? i stretchable<$>)) (define-values (w* h*) (send (car i) get-max-extent x y)) (values (cons (list w* h*) res) (x-extent w w*) (y-extent h h*) (x-draw x w*) (y-draw y h*))) (else (define-values (w* h* l t r b) (send (car i) get-extent x y)) (values (cons (list w* h* l t r b) res) (x-extent w w*) (y-extent h h*) (x-draw x w*) (y-draw y h*))))) ((res (quote ())) (w 0) (h 0) (x (+ l sx)) (y (+ t sy)) #:result (values (reverse res) (max sw (+ w l r)) (max sh (+ h t b)) l t r b)) ((i (in-list editor-list))) (cond ((and stretchable? (is-a? i stretchable<$>)) (define-values (w* h*) (send (car i) get-max-extent x y)) (values (cons (list w* h*) res) (x-extent w w*) (y-extent h h*) (x-draw x w*) (y-draw y h*))) (else (define-values (w* h* l t r b) (send (car i) get-extent x y)) (values (cons (list w* h* l t r b) res) (x-extent w w*) (y-extent h h*) (x-draw x w*) (y-draw y h*)))))
>

**Comment by spdegabrielle** [comment]
@LeifAndersen

**Comment by LeifAndersen** [comment]
Oh wow. I just noticed this issue. I'm sorry for the _really_ late response... Anyway, this repo is in a super early state of development, and so the tests will be up and down for a bit.

Thanks for checking it out thought. And I will do some re-structuring of the repo soon, so that hopefully the tests will pass. (I might also rename the repo to something more meaningful than just "idmt". ;) )

**Comment by spdegabrielle** [comment]
Hi @LeifAndersen I like new name :smile:
